spring.application.name=BillingSystem
spring.datasource.url=jdbc:mysql://localhost:3306/billingdb
spring.datasource.username=root
spring.datasource.password=Ashvini@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
